spring.application.name=book

spring.datasource.url=jdbc:sqlite:booking_system.db?foreign_keys=true
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

spring.main.banner-mode=OFF
logging.level.jdbc=OFF
logging.level.org.community.booking=DEBUG
spring.jackson.deserialization.fail-on-null-for-primitives=false


server.forward-headers-strategy=framework
